service: my-flea-market-notifier

frameworkVersion: '3'
plugins:
  - serverless-esbuild
  - serverless-offline
custom:
  esbuild:
    bundle: true
    platform: node
    target: node22
    sourcemap: true          # 핵심
    sourcesContent: true     # 추천(WSL/컨테이너/상대경로 꼬임 방지)
    keepNames: true          # 선택(스택트레이스 가독성)
  serverless-offline:
    httpPort: 3003
    lambdaPort: 3004 # default: 3002

useDotenv: true

provider:
  name: aws
  runtime: nodejs22.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-northeast-2'}
  # memorySize: 256
  timeout: 30
  deploymentBucket:
    # Name of an existing bucket to use (default: created by serverless)
    name: ${env:DEPLOYMENT_BUCKET}
    # On deployment, serverless prunes artifacts older than this limit (default: 5)
    maxPreviousDeploymentArtifacts: 5
    # Prevents public access via ACLs or bucket policies (default: false)
    # Note: the deployment bucket is not public by default. These are additional ACLs.
    blockPublicAccess: true
    # Skip the creation of a default bucket policy when the deployment bucket is created (default: false)
    # skipPolicySetup: true
    # Enable bucket versioning (default: false)
    # versioning: true
    # Server-side encryption method
    serverSideEncryption: AES256
    # For server-side encryption
    # sseKMSKeyId: arn:aws:kms:us-east-1:xxxxxxxxxxxx:key/aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa
    # For server-side encryption with custom keys
    # sseCustomerAlgorithim: AES256
    # sseCustomerKey: string
    # sseCustomerKeyMD5: md5sum
  tracing:
    lambda: true
    apiGateway: true
  iam:
    deploymentRole: "arn:aws:iam::${aws:accountId}:role/my-flea-market-role-CloudFormationExecutionRole"
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: '*'
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:Scan
            - dynamodb:Query
            - dynamodb:UpdateItem
            - dynamodb:DescribeStream
            - dynamodb:GetRecords
            - dynamodb:GetShardIterator
            - dynamodb:ListStreams
          Resource:
            - arn:aws:dynamodb:${self:provider.region}:*:table/${env:DYNAMODB_PREFIX}*
            - arn:aws:dynamodb:${self:provider.region}:*:table/${env:DYNAMODB_PREFIX}*/stream/*
        - Effect: Allow
          Action:
            - sns:Publish
          Resource:
            - Ref: NotifierSNSTopic
  environment:
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
    DYNAMODB_PREFIX: ${env:DYNAMODB_PREFIX}
    TELEGRAM_BOT_TOKEN: ${env:TELEGRAM_BOT_TOKEN}

    SNS_TOPIC_ARN:
      Ref: NotifierSNSTopic

functions:
  noop:
    handler: src/handlers/noop.handler

  # capture updates from dynamodb stream
  processDynamoDBStream:
    handler: src/handlers/processDynamoDBStream.handler
    events:
      - stream:
          type: dynamodb
          arn: # get arn from other serverless service
            Fn::ImportValue: ${env:DYNAMODB_PREFIX}-items-ItemTableStreamArn
          batchSize: 5
          startingPosition: LATEST

  notifier:
    handler: src/handlers/notifier.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - NotifierSQSQueue
              - Arn
          batchSize: 5

resources:
  Resources:
    # SNS Topic to receive notifications
    NotifierSNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: my-flea-market-${self:provider.stage}-items-notifier-topic
    # SQS Queue to receive messages from SNS
    NotifierSQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: my-flea-market-${self:provider.stage}-items-notifier-queue
        VisibilityTimeout: 60

    NotifierSQSSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn:
          Ref: NotifierSNSTopic
        Protocol: sqs
        Endpoint:
          Fn::GetAtt:
            - NotifierSQSQueue
            - Arn
